### ISSUE TITLE
Issue with gpfs_filesetquota metrics collect

### ISSUE THREAD

**Issue by SckyzO** [IBM/ibm-spectrum-scale-bridge-for-grafana#191]
Hello, 

I use metrics_gpfs_filesetquota, and i have an issue ... very strange i don't know why. There are some holes in my metrics collection (all the time 5min), and that's something I don't have with other endpoints. 

![image](https://github.com/IBM/ibm-spectrum-scale-bridge-for-grafana/assets/683678/44dff27c-a389-4197-9b22-9abb7c9c2f7f)

```yaml
  - job_name: 'gpfs_filesetquota'
    scrape_interval: 5m
    scrape_timeout: 2m
    metrics_path: '/metrics_gpfs_filesetquota'
    static_configs:
      - targets: ['localhost:9250']
        labels:
          env: qualif
          cluster: gpfs
    honor_timestamps: True
    scheme: https
    tls_config:
      cert_file: /etc/bridge_ssl/certs/cert_brige_ibm.pem
      key_file: /etc/bridge_ssl/certs/privkey_brige_ibm.pem
      insecure_skip_verify: True
```

I don't think I made a configuration error, if you have an idea I'll take it
