### ISSUE TITLE
Grafana operator and supported Grafana version

### ISSUE THREAD

**Issue by olemyk** [IBM/ibm-spectrum-scale-bridge-for-grafana#52]
As discussed:

In the YAML example **grafana-operator-subscription.yaml,** it points to the alpha channel, and that is version 3.x of the Operator.. 
And if I read the operator text they recommend using v4.

And in the support-matrix we are stating support for Grafana 8. and above.  
However, the current version for Grafana in OpenShift it's v.7.5.11. 
Please separate the support matrix for CSNA and Standalone/classic Setup.  

```
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: grafana-operator-subscription
  namespace: grafana-for-cnsa
spec:
  channel: **alpha => v4**
  name: grafana-operator 
  source: community-operators 
  sourceNamespace: openshift-marketplace 
```
